Repository dev-ant/sql-interpreter-android, pull requests merged in 2024-04, with the labels that each got.

#40 [infra] Configure github actions unit test workflow
  .github/workflows/android-build.yml
  .github/workflows/unit-test.yml
  app/build.gradle
  app/src/main/java/com/csapp/sqli/viewmodel/EditorViewModel.kt
  app/src/test/java/com/csapp/sqli/ExampleUnitTest.kt
  app/src/test/java/com/csapp/sqli/viewmodel/EditorViewModelTest.kt
Labels: infra, Incompleteness

#44 [refactor] Improve editor view model readability and fun call frequency
  app/src/main/java/com/csapp/sqli/model/LineNumber.kt
  app/src/main/java/com/csapp/sqli/view/EditorActivity.kt
  app/src/main/java/com/csapp/sqli/viewmodel/EditorViewModel.kt
  app/src/main/res/layout/activity_editor.xml
Labels: refactor

#46 [refactor] Separate line number logic from editor view model
  app/src/main/java/com/csapp/sqli/utils/LineNumberManager.kt
  app/src/main/java/com/csapp/sqli/viewmodel/EditorViewModel.kt
Labels: refactor

#47 Resolve the no tests found issue in the github action unit test
  .github/workflows/android-build.yml
  .github/workflows/unit-test.yml
Labels: infra, fix

#52 [refactor] Apply coroutine to asynchronous execution of database
  .github/workflows/playstore-update.yml
  app/build.gradle
  app/build.gradle.kts
  app/proguard-rules.pro
  app/src/main/java/com/csapp/sqli/repository/DatabaseRepository.kt
  app/src/main/java/com/csapp/sqli/utils/LineNumberManager.kt
  app/src/main/java/com/csapp/sqli/view/EditorActivity.kt
  app/src/main/java/com/csapp/sqli/viewmodel/EditorViewModel.kt
  app/src/test/java/com/csapp/sqli/utils/LineNumberManagerTest.kt
  build.gradle
  build.gradle.kts
  settings.gradle.kts
Labels: refactor
